### PR TITLE
Api endpoints

### PR DESCRIPTION
**Pull request by HFG43**
Hi there! We are sending this pull request for you to review our code. Thanks in advance for your feedback!

Milestones 🎯:
📌 Work on Pair Programming
📌 Create an API endpoint to list all posts for a user.
📌 Create an API endpoint to list all comments for a user's post.
📌 Create an API endpoint to add a comment to a post. 
📌 Ensure API posts JSON & GETS JSON as well

📌 Please, find below our API references

| Verb | URI | body | response |
|---|---|---|---|
| GET | /users/:user_id/posts | N/A | [ { post1 } , { post2 } ]|
| GET |  /users/:user_id/posts/:post_id/comments |  N/A | [ { comment1 }, { comment2 } ] |
| POST |  /users/:user_id/posts/:post_id/comments | { "comment": { "text": "your comment" } } | { comment } |

🎖️ General requirements:
Gitflow
No linter errors
Ensure the use of best practices and Ruby style

### CODE REVIEW

**Comment by topeogunleye** [comment]
Hi @HFG43, @HFG43

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I hope you're doing well. After reviewing your project, I faced an issue when trying to create the database. I consulted with a Senior Code Reviewer, and they faced the same error on their end as well.

This suggests that there might be a configuration issue or something missing in your project setup. One of the common reasons for such issues could be related to the `bin` folder or some specific setup configurations. 

Remember, challenges like these are a part of the learning process. Keep pushing forward! 💪

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by HFG43** [comment]
@topeogunleye Thanks for your reply, is it possible for you to share a screenshot or detail of the error?

**Comment by HFG43** [comment]
Please, find here what was taken as error previously. 
WhatsApp Image 2023-10-06 at 19 09 44

Here you will find a print screen on our side when we run the commands:
WhatsApp Image 2023-10-06 at 19 20 20

**Review by addod19 — APPROVED** [review]
## Hi @HFG43 and @ahmedeid6842, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] README file is professional :fireworks: 
- [ ] API endpoints look great and work as intended :rocket: 
- [ ] Awesome collaborative work :rocket: 
- [ ] Migration works as intended :100: 
Screenshot from 2023-10-06 23-15-53



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> @topeogunleye Thanks for your reply, is it possible for you to share a screenshot or detail of the error? As it is the same database we have been using before

Replied on slack. ✔️

**Pull request merged**
